platform :ios, '10.0'

source 'https://github.com/Seras3/react-native-ios-private-repo.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'MySdk-poc' do
  use_frameworks!
  
  # path to the sdk
  pod 'MySdk-native', :path=> '../MySdk-native'


end